Ext.onReady(function(){
	Ext.QuickTips.init();
	Ext.create('Ext.form.Panel',{
		title:'Ext.form.FieldContainer示例',
		width:300,
		height:100,
		frame:true,
		renderTo:'form',
		bodyPadding:5,
		fieldDefaults:{
			laberSeparator:':',
			labelWidth:70,
			width:260,
			msgTarget:'side'
		},
		defaultType:'textfield',
		items:[
			{
				fieldLabel:'商品名称'
			},
			{
				fieldLabel:'生产日期',
				xtype:'fieldcontainer',
				layout:{//设置容器字段布局
					type:'hbox',
					align:'middle'
				},
				combineErrors:true,//是否集成起来显示错误信息
				fieldDefaults:{
					//hideLabel:true,
					allowBlank:false
				},
				defaultType:'textfield',
				items:[
				{
					hideLabel:true,
					fieldLabel:'年',
					flex:1,
					inputId:'yearId'
				},
				{
					xtype:'label',
					forId:'yearId',
					text:'年'
				},
				{
					hideLabel:true,
					fieldLabel:'月',
					flex:1,
					inputId:'monthId'
				},
				{
					xtype:'label',
					forId:'monthId',
					text:'月'
				},
				{
					hideLabel:true,
					fieldLabel:'日',
					flex:1,
					inputId:'dayId'
				},
				{
					xtype:'label',
					forId:'dayId',
					text:'日'
				}
				]
			}
		]
	});
})